# .github/workflows/release.yml
on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  build_addon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set VERSION env
      run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV
    # Upload to Steam Workshop
    - uses: arma-actions/workshop-upload@v1
      with:
        appId: '294100'    # default
        itemId: '2610120706' # Id of item to update
        contentPath: 'releases/${{ env.VERSION }}/@IwoRosiak'
        changelog: 'Content of change notes'
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
